### ISSUE TITLE
json netflixID

### ISSUE THREAD

**Issue by phantomdiorama** [jaredsohn/flix_plus#10]
The netflixID values in the exported mylist json are not correct. Looks like it's choosing the number which they appear in the mylist list rather than the actual trackid number of the movie/show.

**Comment by jaredsohn** [comment]
Pretty much all of the My List functionality is broken due to Netflix's changes; a new version is coming in the next day or so; I'll verify this is right before releasing.

**Comment by jaredsohn** [comment]
FYI, Flix Plus was updated today so this should be fixed now.
