### ISSUE TITLE
Keyboard navigation does not move through the "Who's watching?" (profiles) screen.

### ISSUE THREAD

**Issue by Joshfindit** [jaredsohn/flix_plus#4]
When launching Netflix, this is the first screen if profiles are enabled.

The HTML for each menu item is:

    <li class="profile" data-reactid=".#">
      <a class="profileItem pointer" data-reactid="#">
        <img class="" src="https://secure.netflix.com/en_us/ffe/avatars_v2/112x112/PICON_025.png" alt="NAME" data-reactid="#">
        <span class="profileName" data-reactid="#">NAME</span>
      </a>
    </li>

**Comment by jaredsohn** [comment]
Already done (will be in next release.)
