### ISSUE TITLE
Link to RT is broken

### ISSUE THREAD

**Issue by Gabriel-p** [jaredsohn/flix_plus#6]
Apparently the feature no longer works: http://developer.rottentomatoes.com/forum/read/110751/2

An API key seems to be necessary now: http://developer.rottentomatoes.com/docs/read/json/v10/Movie_Alias

**Comment by jaredsohn** [comment]
We aren't using Rotten Tomatoes' API; we are using omdbapi.com.  Are you experiencing problems regarding these ratings within the extension?

**Comment by Gabriel-p** [comment]
Yes, this is the link for 'Sin City' for example:

http://www.rottentomatoes.com/alias?type=imdbid&s=0458481

**Comment by jaredsohn** [comment]
I see it now; the site's changes don't affect our ability to get the ratings, but they do affect the links we create.  I'll see if it makes sense to include an API key or make some other change (if getting an API key doesn't work, the 'links' script just does a search without the imdb id, although that isn't as useful.)

**Comment by jaredsohn** [comment]
I updated the extension today to link to a search.  Thanks for letting me know it was broken.

**Comment by Gabriel-p** [comment]
Thank you Jared!
