### ISSUE TITLE
export to json

### ISSUE THREAD

**Issue by phantomdiorama** [jaredsohn/flix_plus#8]
Does exporting My List to json no longer work?

**Comment by jaredsohn** [comment]
It looks like it has been broken since sometime during the summer. I will post a fix early next week.

**Comment by jaredsohn** [comment]
A fix has been posted in Flix Plus v3.11.

**Comment by phantomdiorama** [comment]
Exporting works now. However the netflixID values are not correct. Looks like it choosing the number which they appear in the mylist list rather than the actual  id number.
